In [ ]:
# Q1.  1. Explain pandas and its role in Data Analysis and Machine Learning. 

# ANS:
# Pandas is an open-source Python library used for structured data manipulation, 
# analysis, and cleaning. Built directly on top of NumPy, 
# it provides fast, flexible data structures that mimic Excel spreadsheets or SQL tables,
# allowing users to process large amounts of data with minimal code.

# Core Data StructuresSeries: 
# A 1-dimensional labeled array capable of holding any data type.DataFrame: 
# A 2-dimensional tabular structure with labeled rows and columns.


# Role in Data Analysis
# Pandas acts as the primary tool for Exploratory Data Analysis (EDA) by bridging the gap between raw data collection and deep analytical insight.
# Data Ingestion: Reads multiple file formats including CSV, Excel, JSON, and SQL.
# Descriptive Statistics: Generates instant metrics (mean, median, standard deviation) via methods like .describe().
# Slicing and Filtering: Extracts specific rows or columns matching intricate logical conditions.
# Aggregation: Segregates data using .groupby() to calculate summaries across distinct subsets.
# Time-Series Analysis: Provides robust tools to re-sample, shift, and window dates and timestamps.


# Role in Machine Learning
# Machine learning algorithms require perfectly formatted numerical arrays to run. 
# Pandas serves as the critical data preprocessing and feature engineering engine before data reaches a model.
# Handling Missing Values: Detects and resolves null fields using .isnull(), .fillna(), or .dropna().
# Categorical Encoding: Converts text categories into model-ready numbers using one-hot encoding via pd.get_dummies().
# Feature Engineering: Derives new mathematical columns from existing variables to capture better predictive signals.
# Dataset Splitting & Merging: Joins separate data matrices or maps targets using .merge() and .concat().
# Downstream Integration: Converts clean DataFrames into structured multi-dimensional arrays accepted by Scikit-learn, TensorFlow, and PyTorch.

In [ ]:
# Q2. Differentiate between: 
# ● Series and DataFrame  
# ● loc[] and iloc[] functions in Pandas

# ANS

# difference between series and dataframe

# Series                                                     #DataFrame
#.1-Dimensional array.                                        .2-Dimensional tabular structure.
#.Contains a single column of data with an index.             .Contains rows and columns (like a spreadsheet)
#.Data TypesEvery element shares the same data type.          .Different columns can have different data types.
#.CreationFormed from a list, dictionary, or 1D array.        .Formed from a dictionary of lists, 2D array, or files like CSVs.


#difference between loc[] and iloc[] Functions

#loc[]                                                         #iloc[]

#.Label-based indexing.                                       .Integer position-based indexing.
#.Accepts explicit row/column names (e.g., 'Age').            .Accepts numerical index numbers (e.g., 0, 1, 2).
#.The stop index is included (e.g., a:b includes b).          .The stop index is excluded (e.g., a:b drops b)
#.Fully supports filtering using direct boolean masks.        .Raises a ValueError if passed a boolean Series directly.

In [1]:
import os
import numpy as np
import pandas as pd

In [ ]:
#Q3.
data = {
    "Name": ["Amit", "Neha", "Rahul", "Sneha"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 90, 78, 88]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
2  Rahul   19     78
3  Sneha   22     88

In [ ]:
#3 
# task(a1)
df.head(2)

   Name  Age  Marks
0  Amit   20     85
1  Neha   21     90

In [ ]:
#3 
# task(a2)
df[["Name", "Marks"]]

    Name  Marks
0   Amit     85
1   Neha     90
2  Rahul     78
3  Sneha     88

In [ ]:
#3
# task(a3)
df["Result"] = ["Pass" if marks >= 80 else "Fail" for marks in df["Marks"]]
df

    Name  Age  Marks Result
0   Amit   20     85   Pass
1   Neha   21     90   Pass
2  Rahul   19     78   Fail
3  Sneha   22     88   Pass

In [ ]:
#3
# task(a4)
df[df["Marks"] > 80]

    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
3  Sneha   22     88

In [ ]:
#3
# b1.
df = pd.DataFrame(data)
df

    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
2  Rahul   19     78
3  Sneha   22     88

In [14]:
#3
# b2.
df.head()

    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
2  Rahul   19     78
3  Sneha   22     88

In [15]:
#3
# b3.
df[["Name", "Marks"]]

    Name  Marks
0   Amit     85
1   Neha     90
2  Rahul     78
3  Sneha     88

In [16]:
#3
# b4.
df[df["Marks"] > 80]

    Name  Age  Marks
0   Amit   20     85
1   Neha   21     90
3  Sneha   22     88

In [17]:
#4.
data = {
    "Name": ["A", "B", "C", "D"],
    "Age": [25, np.nan, 27, 24],
    "Salary": [30000, 40000, "NaN", 35000]
}

df = pd.DataFrame(data)
df

  Name   Age Salary
0    A  25.0  30000
1    B   NaN  40000
2    C  27.0    NaN
3    D  24.0  35000

In [19]:
#4
# a1.
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False   False
3  False  False   False

In [20]:
#4
# a2.
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

  Name        Age Salary
0    A  25.000000  30000
1    B  25.333333  40000
2    C  27.000000    NaN
3    D  24.000000  35000

In [21]:
#4
# a3.
df["Salary"] = df["Salary"].fillna(df["Salary"].median())
df

  Name        Age Salary
0    A  25.000000  30000
1    B  25.333333  40000
2    C  27.000000    NaN
3    D  24.000000  35000

In [22]:
#4
# a4.
print("\nCleaned Dataset:")
print(df)

Cleaned Dataset:
  Name        Age Salary
0    A  25.000000  30000
1    B  25.333333  40000
2    C  27.000000    NaN
3    D  24.000000  35000

In [23]:
#4
# b1.
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False

In [24]:
#4
# b2
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

  Name        Age Salary
0    A  25.000000  30000
1    B  25.333333  40000
2    C  27.000000    NaN
3    D  24.000000  35000

In [25]:
#4
# b3.
df["Age"].mean()

np.float64(25.333333333333332)

In [26]:
#4
# b4.
df["Salary"].median()

np.float64(35000.0)

In [30]:
#5
df=pd.read_csv(r"C:\Users\abc\OneDrive\Desktop\Data Science\assignment\Iris.csv")

In [31]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
# a
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [34]:
print("\nRows and Columns:")
print(df.shape)

Rows and Columns:
(150, 6)

In [35]:
print("\nAverage Sepal Length:")
print(df["SepalLengthCm"].mean())

Average Sepal Length:
5.843333333333334

In [39]:
print(df["Species"].unique())

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [38]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [40]:
#5
# b
df = pd.read_csv(r"C:\Users\abc\OneDrive\Desktop\Data Science\assignment\Iris.csv")

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB

In [42]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [43]:
df["Species"].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str